export default [
  {
    sku: 1, 
    product: "Lara",  
    description: "Koupelnová předložka",    
    details: "Nadčasový, moderní interiér si zaslouží důstojný doplněk. Šedá předložka Arolo s nápaditým detailem dotvoří každý interiér například v oblíbeném black and white stylu.",
    image: "/shop/44.png",
    images: [
          { image: "/shop/24.png" },
          { image: "/shop/20.png" },
          { image: "/shop/22.png" },
          { image: "/shop/46.png" }
        ],
    color: [ "red" , "black" ],          
    price: 12.00,
  },
  {
    sku: 2,
    product: "Arolo",  
    description: "Koupelnová předložka",
    details: "Nadčasový, moderní interiér si zaslouží důstojný doplněk.",
    image: "/shop/20.png",
    color: [ "red","hotpink" ],          
    price: 13.00,
  },
  {
    sku: 3,
    product: "Masandra",  
    description: "Koupelnová předložka",
    details: "This is where some detailes on predlozka would go.",
    image: "/shop/22.png",
    color: ["gray" ],  
    price: 14.00,
  },
  {
    sku: 4,
    product: "Adamov",  
    description: "Koupelnová předložka",
    details: "Supersoft Polyakryl 100%",
    image: "/shop/24.png",
    price: 11.00,
    color: ["green"],  
  },
  {
    sku: 5,
    product: "Afrodita",  
    description: "Koupelnová předložka k vane",
    details: "Supersoft Polyakryl 100% ",
    image: "/shop/46.png",
    price: 25.00,
    color: ["gray"],  
  },
  {
    sku: 6, 
    product: "Circle",  
    description: "Koupelnová předložka k vane",
    details: "This is where some detailes Barevné varianty",
    image: "/shop/28.png",
    price: 12.99,
    color: ["gray","blue"],  
  },
  {
    sku: 7,
    product: "Whild Rose",  
    description: "Koupelnová předložka k vane",
    details: "Protiskluzové podložky do vany.",
    image: "/shop/30.png",
    price: 2.05,
    color: ["red"],  
  },
  {
    sku: 8,
    product: "Sinerise",  
    description: "Koupelnová předložka k vane",
    details: "Studenti umělecké textilní školy",
    image: "/shop/32.png",
    price: 22.08,
    color: ["gray"], 
  },
  {
    sku: 9,
    product: "Beautiful",  
    description: "Koupelnová předložka k vane",
    details: "Studenti umělecké textilní školy navrhli.",
    image: "/shop/34.png",
    price: 11.12,
    color: ["indigo","gray"],  
  },
  {
    sku: 10,
    product: "Creative",  
    description: "Koupelnová předložka",
    details: "Studenti umělecké textilní školy navrhli.",
    image: "/shop/36.png",
    price: 122.34,
    color: ["red"],  
  },
  {
    sku: 11,
    product: "Aurora",  
    description: "Koupelnová předložka k vane",
    details: "Studenti umělecké textilní školy navrhli.",
    image: "/shop/38.png",
    price: 1.67,
    color: ["red"] 
  },
  {
    sku: 12,
    product: "Black sea",  
    description: "Koupelnová předložka",
    details: "Studenti umělecké textilní školy navrhli.",
    image: "/shop/40.png",
    price: 12.99,
    color: ["blue"],   
  },
  {
    sku: 13,
    product: "Orange beach",  
    description: "Koupelnová předložka",
    details: "Studenti umělecké textilní školy navrhli.",
    image: "/shop/26.png",
    price: 10.99,
    color: ["orange"],     
  },
  {
    sku: 14,
    product: "Beauty",  
    description: "Koupelnová předložka",
    details: "Studenti umělecké textilní školy navrhli.",
    image: "/shop/42.png",
    price: 10.99,
    color: ["blue"],     
  },
  {
    sku: 15,
    product: "Rainbow",  
    description: "Koupelnová předložka",
    details: "Studenti umělecké textilní školy navrhli.",
    image: "/shop/4.png",
    price: 10.99, 
     color: ["blue","red"],       
  },
  {
    sku: 16,
    product: "Sink",  
    description: "Koupelnová předložka",
    details: "Studenti umělecké textilní školy navrhli.",
    image: "/shop/18.png",
    price: 11.99,
    color: ["gray"],     
  },
  {
    sku: 17,
    product: "Cancer",  
    description: "Koupelnová předložka",
    details: "Studenti umělecké textilní školy navrhli.",
    image: "/shop/11.png",
    price: 9.99, 
    color: ["green"],        
  },   
  {
    sku: 18,
    product: "Kvitka",  
    description: "Koupelnová předložka",
    details: "Studenti umělecké textilní školy navrhli.",
    image: "/shop/3.png",
    price: 10.99, 
     color: ["gray","indigo"],       
  },
  {
    sku: 19,
    product: "Zebra",  
    description: "Koupelnová předložka",
    details: "Studenti umělecké textilní školy navrhli.",
    image: "/shop/5.png",
    price: 11.99,
    color: ["black"],     
  },
  {
    sku: 20,
    product: "Lavata",  
    description: "Koupelnová předložka",
    details: "Studenti umělecké textilní školy navrhli.",
    image: "/shop/6.png",
    price: 9.99, 
    color: ["red","black"],        
  },                 
       
]
